### ISSUE TITLE
OnePlus 5 only eye camera is working

### ISSUE THREAD

**Issue by KhaledSaleh** [pupil-labs/pupil-mobile-app#12]
Hello

I'm trying the pupil mobile with my tracker which has the high resolution world camera, when I connect it to my OnePlus 5 phone I only can see the feed coming from the eye camera but the world camera feed is not showing anything nor sending to the pupil capture !?

**Comment by mkassner** [comment]
@KhaledSaleh  please try to reset the app settings. This should re-query the permissions and fix your problem.
