### ISSUE TITLE
Auto-Exposure Priority and Wifi

### ISSUE THREAD

**Issue by AprilRG** [pupil-labs/pupil-mobile-app#13]
When I am on wifi, I can change this setting to the frame rate may be dynamically altered. But, when I disconnect from wifi, I cannot change this setting. This makes it very difficult to do a study outside.

**Comment by mkassner** [comment]
Usually changing settings is locked during recording, maybe this was the case?

**Comment by mkassner** [comment]
@saki4510t  apparently this is not related to recording. Can you check?

**Comment by AprilRG** [comment]
I am using a Samsung Galaxy s8. I know it's not an approved phone, so if it's the phone I'll see if I can get some funds for a new one.

Here's what I did: 
I started not connected to the wifi and not recording. I have the glasses facing outside so it's bright and I could see if the setting changed immediately. I opened the Pupil Cam1 ID2  and tapped the upper left button for settings. Then tried to change the auto-exposure priority to the frame rate may be dynamically varied by the device. When I click it, the setting looks changed but the camera doesn't actually change and if I reopen the settings tab, it's back at the frame rate must remain constant. I tried the same process connected to wifi, and then it worked. Upon further investigation I found none of the settings following the line under the frame rate setting were possible to change when I was not connected to wifi.

**Comment by saki4510t** [comment]
@mkassner 
As you requested, app resets camera settings for eye camera(s) every time when app starts using camera (for getting setting from camera, preview, recording and publishing to Pupil Capture).

**Comment by mkassner** [comment]
@saki4510t  I think this discussion is about the world camera.

**Comment by AprilRG** [comment]
@saki4510t I meant the world camera, sorry for not including it. My world videos are overexposed because I can't change this setting when I'm not on Wi-Fi.

**Comment by saki4510t** [comment]
Sorry for my confusion, I will check/confirm and improve.

**Comment by saki4510t** [comment]
@AprilRG 
I mistook handling of camera settings for world camera and will fix on r0.23.0 (released now)
