### ISSUE TITLE
How to load a mobile recording into pupil player?

### ISSUE THREAD

**Issue by emolyzr** [pupil-labs/pupil-mobile-app#17]
I do not understand the data structure that is saved on the SD card of the mobile phone. There are three folders, obviously one for each CAM (world, eye0, eye1). However, I can only drop one folder into the pupil player app. I also cannot merge the folders, since info.csv exists three times. How do deal with that?

<img width="502" alt="ordner" src="https://user-images.githubusercontent.com/35568338/39399246-d0c407a0-4b1a-11e8-8b92-2326770e8aaa.png">
Content Folder 1
<img width="509" alt="ordner1_inhalt" src="https://user-images.githubusercontent.com/35568338/39399248-d537afda-4b1a-11e8-8173-bd642ff7b3bf.png">

Content Folder 2
<img width="525" alt="ordner2_inhalt" src="https://user-images.githubusercontent.com/35568338/39399249-d5507894-4b1a-11e8-9124-48582873fb4d.png">

Content Folder 3
<img width="960" alt="ordner3_inhalt" src="https://user-images.githubusercontent.com/35568338/39399247-d51db36e-4b1a-11e8-85f7-0e4d1648e316.png">

On a second recording, I tried, there is even one cam missing...

**Comment by willpatera** [comment]
@emolyzr Could you let us know what Android device you are using? There should be video files for each camera that was enabled and audio/imu if enabled. Additionally you should see timestamp `.time` files and `info.csv` file all within **one** folder.

**Comment by emolyzr** [comment]
I am using Motorola Z2 Play, as recommended. Encountered this now multiple times.

**Comment by papr** [comment]
@emolyzr Did you use Remote Recorder to start the recording? This is a known issue and is ebing fixed in one of the upcoming updates. In the mean time, copy all `.mjpeg` and `.time` files into a single folder, add one of the `info.csv` files as well and drop that folder onto Player.

**Comment by emolyzr** [comment]
Our WiFi connection was completely down, and we therefore wanted to make local recordings, i.e. directly recording using only the app. I try the copy-paste workaround.

**Comment by papr** [comment]
Just to clarify: You used the main-recording button in the Pupil Mobile to make the recordings above?

**Comment by emolyzr** [comment]
For the above recording, I am not 100% sure, but I guess "yes". 

However, we made some recordings, for which we didn't had WiFi and that are split up into three folders (one per cam) just like the recording above. That is, without the smartphone being connected to any WiFi, we used the main-recording button in the Pupile Mobile App to make the above recordings.

**Comment by mkassner** [comment]
I think this is fixed and I will close this issue now.
