### ISSUE TITLE
Capture-Publishing Mode / Some experiences

### ISSUE THREAD

**Issue by emolyzr** [pupil-labs/pupil-mobile-app#20]
Just some experiences to simultaneous recording on smartphone and streaming via wifi:
- Smartphone gets extremely hot (Moto Z2 Play)
- Sometimes on button press to start a recording some but not all modules switch status to capture, e.g. 2 cams are capture-publishing but 1 cam is only publishing. Sometimes audio is not captured. Stop and restart helps in these situations.
- Synchronous Capturing and Publishing leads to small fps-rates with my device (moto z2 play, which is the recommended at the moment), 10-15 fps, sometimes 5 fps, which is not visible in pupil capture stats, there it says "28 fps" in the right upper corner, but you can see that samplerate of the pics is low as they come in one by one. 
- If I record both recordings (local on smartphone, and the wifi-streamed data) both recordings are recorded with the low fps, meaning that the smartphone and not the wifi is the bottleneck.

So in my view: I cannot recommend capture-publishing at the moment, except for uses cases where 5 fps is enough (as in our use case ;)

**Comment by mkassner** [comment]
I recommend not having the phone in a pocket but rather outside. We test  using the moto z2 and z3 play. We find that you can record at full framerate fine. Streaming and recording at the same time can lead to frame-rate decrease. We recommend streaming only for preview and recording for most of the experiment.
