### ISSUE TITLE
Reading IMU file

### ISSUE THREAD

**Issue by phev8** [pupil-labs/pupil-mobile-app#24]
I couldn't find any instruction or hint how to open the IMU files recorded by the app. I see that both the imu_xx.imu and imu_xx.time files contain binary values. Does the Pupil Player has any csv export function for IMU data?

**Comment by papr** [comment]
Hey @phev8 
Pupil Player does not support IMU data import/export yet. See this issue https://github.com/pupil-labs/pupil-mobile-app/issues/5#issuecomment-295168255 on how to read the time files.

@saki4510t could you elaborate on the `*.imu` data format?

**Comment by phev8** [comment]
Thanks @papr. I could read the time files based on the comment you mentioned. But I'm still struggling with the IMU data. Assuming it has the same number of rows, than the time file, each row would then contain 960 bytes or so. I was trying to read values with converting simply each 4 or 8 byte into a float/double value, but the numbers are huge then, so probably doing it wrong.

**Comment by mkassner** [comment]
@saki4510t  can you quickly explan the imu data format here?

**Comment by saki4510t** [comment]
Data in `.imu` file are as follows;
One data is 3 float32 values and 80 data packed into one frame. 
App also write timestamp values into `.time` file for each frame (==every 80 data) and when app write last data(the last frame may be 1-80 data).

```
Data: (`imu_data_t[80]`) x (n frames, n >= 0) + `imu_data_t[0..79]`
typedef struct imu_data {
    float32_t accel_x_be;
    float32_t accel_y_be;
    float32_t accel_z_be;
} __attribute__ ((packed)) imu_data_t;
```

**Comment by phev8** [comment]
Thanks for the answer. That helped me to read the file.
