### ISSUE TITLE
Gaze mapping

### ISSUE THREAD

**Issue by mahbub2251** [pupil-labs/pupil-mobile-app#25]
How to load the gaze mapping from the mobile recordings? 

I can only enable the Vis Circle or Vis Polyline from the player if the recording is from the computer. How can I track the pupil if it is from mobile recording?

**Comment by papr** [comment]
Hey, please see the offline pupil detection and offline calibration instructions in our documentation for this information.

**Comment by olliraa** [comment]
Hi.

having the same problems. My main problem is this: where do I calibrate when using Pupil Mobile? You said:

> > 3. Start recording (on Android).
> 4. Perform calibration routine. Concrete example: have the participant (wearer of the Pupil headset) look at the center of a manual marker and perform a single marker calibration -- see docs on calibration routines [here](https://docs.pupil-labs.com/#calibration-methods)

But, how can I start calibration on the Android? Sorry, I must be blind or something :/
