### ISSUE TITLE
Can't load recording from Pupil Mobile in Pupil player

### ISSUE THREAD

**Issue by nothaoyi** [pupil-labs/pupil-mobile-app#31]
I have a very same issue #29 , however renaming the files did not solve this problem.

This is what the contents of the folder look like after copying it from the phone to my pc:

![unbenannt](https://user-images.githubusercontent.com/28780612/50041097-811ba600-004f-11e9-9e47-3421657df51f.PNG)

Error log:
[INFO] player_methods: Updating meta info
player - [INFO] player_methods: Checking for world-less recording
player - [ERROR] launchables.player: Could not generate world timestamps from eye timestamps. This is an invalid recording.

I am using the Moto Z3 play with Android 8.1.0

Thanks in advance

**Comment by papr** [comment]
Hi @nothaoyi, could you please post a screen shot of the files after having renamed them?

**Comment by nothaoyi** [comment]
![image](https://user-images.githubusercontent.com/28780612/50041195-39961980-0051-11e9-8ca2-a89dc2d6be13.png)

**Comment by papr** [comment]
Please try copying the original info.csv file into the recording, overwriting the existing one, and open the recording in Player again.

**Comment by nothaoyi** [comment]
That solved it!

So do I have to rename and copy the original info.csv file everytime I try to open a local mobile recording on my pc or is there a way around it?

Thanks alot!

**Comment by papr** [comment]
Rename the files before starting Player. Then you can skip copying the original info.csv for the second time
