### ISSUE TITLE
Offline calibration: I just don't get it

### ISSUE THREAD

**Issue by olliraa** [pupil-labs/pupil-mobile-app#33]
Sorry to be so thick headed, but I just cannot get it to work. I can run the offline pupil detection and it works fine. But when I try to run the offline calibration I only get "Not enough reference points" or "no reference marker data to calibrate section 1". I'm totally missing the idea how do I calibrate the cams when recording with Pupil Mobile. I understood that there is not any calibration in the mobile app?

Could someone please give a detailed guide how do I run the offline calibration after the offline pupil detection has been done.

Latest versions of all the software.

Thanks :)

**Comment by papr** [comment]
Hey @olliraa 
Would you mind sharing an example recording with data@pupil-labs.com ? I will have a look if I can spot any procedural issues during the recording.

**Comment by olliraa** [comment]
Just emailed a link to the files :)

**Comment by willpatera** [comment]
Hi @olliraa I have reviewed your recording. You need to include a calibration procedure (with calibration markers) in the recording. Please refer to the offline calibration section in docs here: https://docs.pupil-labs.com/#data-source-plugins

**Comment by olliraa** [comment]
Hi Pablo :)

Thank you so much, I finally got it :D Awesome! Now just to fine tune the
offset and I'm good to go.

All the best,

-Olli

ma 14. tammik. 2019 klo 12.42 Will (notifications@github.com) kirjoitti:
