### ISSUE TITLE
World camera

### ISSUE THREAD

**Issue by ZanderUniBS** [pupil-labs/pupil-mobile-app#35]
Hello,

i attempted to run Pupil Mobile App on Huawei P20 and One Plus 6 both, but in any case world camera has not been shown. I saw only the two eye cameras and their feed. I've installed Pupil Capture v1.10-20 on Win 10 and Pupil Mobile App version 0.31.0-revert.
What could i do in order to see the world camera?

**Comment by papr** [comment]
Hi, can you please connect the headset directly to the computer and verify that the world camera works correctly?

**Comment by ZanderUniBS** [comment]
I have done it. Cameras work properly, even the world one. 
I installed the app https://play.google.com/store/apps/details?id=com.shenyaocn.android.usbcamera on my phone and i see alle three cameras one by one, thus seems it don't have any hardware issue.

**Comment by papr** [comment]
Ok, great! And does the world camera show and preview on the phone when running Pupil Mobile? Make sure it does not show as "offline".

**Comment by ZanderUniBS** [comment]
I don't find world camera in the Pupil Mobile list. How can i check if it is shown as "offline"?
I only see Pupil Cam2 ID1 and Pupil Cam2 ID0.

**Comment by papr** [comment]
Which Android version do you use. There is a known issue where cameras are not detected correctly by the libuvc layer on Android 9

**Comment by ZanderUniBS** [comment]
Both phones have Android 9. Thus, is there a way to solve it? Something that I can do? Thanks for your support.

**Comment by willpatera** [comment]
There is a bug in Android OS v9 (aka Android Pie)  that breaks USB device enumeration for many USB Cameras. This bug also affects Pupil Labs hardware. Therefore if you are using Pupil Mobile on a device runningAndroid v8, we recommend that you do not upgrade yet to Android v9. If you did update to Android v9 and the update broke compatibility with our hardware, fear not we have we have a solution (actually two solutions!) :smile:

Long term solution - We have identified the bug in Android and submitted a fix to the USB subsystem for Android OS.  Our change has been accepted in the official Android repository! It's exciting to be able to fix a problem at the source, especially for such a widely used codebase! However, it will take some time for our fix to trickle through via Android OEM updates.

Short term workaround - We also changes to Pupil Mobile source code that enables you to continue using Pupil Labs hardware in Android v9. The workaround is available in the most recent version of the Pupil Mobile beta release. You can access the beta releases by opting into the beta program here: https://play.google.com/apps/testing/com.pupillabs.pupilmobile
