### ISSUE TITLE
Eyetrackers not registering on One Plus 5T

### ISSUE THREAD

**Issue by JoeCassidy** [pupil-labs/pupil-mobile-app#36]
Hi,

We have recently purchased some new One Plus 5T phones for use with our portable eye trackers. Although I can see the new phones on the pupil capture software on the laptop when both the laptop and phones are connected to our 5G router- I am unable to open either of the eye trackers on both phones. The eye trackers do not show up at all when attaching via the USB-C cables and only the 'remote host' option is listed with the two phones- no source is available. We purchased these phones in particular as they were listed as working well with the pupil labs software- does anyone have an idea what the connection issue may be? The eyetrackers/connection still works with the previous phone (Nexus 5x), but we need both new phones to 'take over' in our project moving forward. It does not seem to matter which orientation I enter the cables etc. I believe the laptop version we are using is pupil capture 1.9.7, and pupil mobile the most recent version from the google play store.

I would be very grateful if anyone could advise ASAP regarding this issue.

Many thanks,

Joe

**Comment by papr** [comment]
Hi @JoeCassidy 
In order for the app to recognize the cameras, you need to enable the `OTG storage` mode in the system settings. Afterwards, you should see the cameras pop up in the app's main view. You can display the camera preview by tapping each entry.

In case that these steps did not work for you, please comment below, and we can reopen the issue.

**Comment by JoeCassidy** [comment]
Hi,

Many thanks for your quick reply- I’m glad to say that this sorted the issue and the phones are now working!

However, there doesn’t seem to be an option to keep that option selected (it resets after 10 mins). Is this your experience with the One Plus 5T? (if you have used it?)

Many thanks,

Kind regards,

Joe

Joe Cassidy
Psychology Technician/Developmental Dynamics Lab Manager
School of Psychology, Faculty of Social Sciences
Room 01.01B, LSB Building
University of East Anglia, Norwich Research Park, Norwich, NR4 7TJ
England, UK

Tel: + 44 (0) 1603 597377
Email: j.cassidy@uea.ac.uk<mailto:j.cassidy@uea.ac.uk> |  Web: www.uea.ac.uk/psy<http://www.uea.ac.uk/psy>

http://www.uea.ac.uk/developmental-dynamics-lab/home

[cid:image002.jpg@01D48BB4.171FA130][cid:image004.jpg@01D48BB4.171FA130]

Gold (Teaching Excellence Framework 2017-2020)
UK Top 15 (The Times/Sunday Times 2019 and Complete University Guide 2019)
World Top 200 (Times Higher Education World University Rankings 2019)

[TEF Gold logo RGB]  [cid:image002.png@01D2E051.A6A10930]  [facebook] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.facebook.com%2Fueaofficial&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607326917&sdata=pyTQ9kfX%2BGVzLQaVA36zvRz3NUKNzsZGgl1qB8A0ERs%3D&reserved=0>   [twitter-old] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.twitter.com%2Funiofeastanglia&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607336922&sdata=rhW%2FsvtQ8oF6fO2Sx8L5vNM4zZC0nHJ8Xb0xbbcoOfI%3D&reserved=0>  [tumblr] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Funiofeastanglia.tumblr.com%2F&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607346935&sdata=fuOaPhn03UegU%2F1sUCokTaEHgIxIft%2BfcR4rgwbtMzM%3D&reserved=0>  [flickr] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.flickr.com%2Funiofeastanglia&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607346935&sdata=mrnMIt%2F%2FYsYW47VWvIfUPkdtzRWU6aS%2FuOPvpr8N34s%3D&reserved=0>  [linkedin] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fedu%2Fschool%3Fid%3D12699&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607356936&sdata=B1x%2Bm5jSnBykN%2FaeMw%2FOKYc0uQ%2FBOcFjEbfdrDVYruk%3D&reserved=0>  [youtube] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.youtube.com%2Fueaofficial&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607356936&sdata=gJZ6Ghe0W9U9f1WA3lkxzHuf%2BQcCyv70j7pT0BYLmBY%3D&reserved=0>  [cid:image008.png@01CF8BB5.50024060] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Finstagram.com%2Funiofeastanglia&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607366940&sdata=t6fhWH3U0kVxtuTFqPD%2B0LtIi1M%2FMHQRPweSGPJoK3E%3D&reserved=0>

Any personal data exchanged as part of this email conversation will be processed by the University in accordance with current UK data protection law and in line with the relevant UEA Privacy Notice.

This email is confidential and may be privileged. If you are not the intended recipient please accept my apologies; please do not disclose, copy or distribute information in this email or take any action in reliance on its contents: to do so is strictly prohibited and may be unlawful. Please inform me that this message has gone astray before deleting it. Thank you for your co-operation.

**Comment by papr** [comment]
Yes, it resets after some time of inactivity. The reset should not happen while the cameras are in use. As far as I know, disabled OTG is a security feature. I do not know how easy it is to enable it permanently.

**Comment by papr** [comment]
To conclude this issue: On OnePlus devices, OTG can be enabled permanently using the [adb (Android Debug Bridge)](https://developer.android.com/studio/command-line/adb). 

Disclaimer:
One can easily find guides with more details but **we do not recommend** to follow them. If you follow them, do so **on your own risk**.

**Comment by JoeCassidy** [comment]
Hi Pablo,

Many thanks for the info- one of the lab members also found these instructions on how to enable OTG permanently on the Oneplus 5t phones- do you think this approach would be suitable?

https://www.xda-developers.com/enable-always-on-otg-oxygenos/

Is there a reason that you don’t recommend permanently enabling this function?

If there is a solid reason/concerns about enabling the OTG the could an alternative be to just put a shortcut to the OTG setting on the homepage of the phone?

Apparently the cameras shut off after 10 minutes recording today (with OTG enabled) during the session- so it sounds like the OTG may have re-set even though the phones were recording- which is why we are keen to make sure that this doesn’t disrupt recordings in the future.

Thanks again,

Kind regards,

Joe

Joe Cassidy
Psychology Technician/Developmental Dynamics Lab Manager
School of Psychology, Faculty of Social Sciences
Room 01.01B, LSB Building
University of East Anglia, Norwich Research Park, Norwich, NR4 7TJ
England, UK

Tel: + 44 (0) 1603 597377
Email: j.cassidy@uea.ac.uk<mailto:j.cassidy@uea.ac.uk> |  Web: www.uea.ac.uk/psy<http://www.uea.ac.uk/psy>

http://www.uea.ac.uk/developmental-dynamics-lab/home

[cid:image002.jpg@01D48BB4.171FA130][cid:image004.jpg@01D48BB4.171FA130]

Gold (Teaching Excellence Framework 2017-2020)
UK Top 15 (The Times/Sunday Times 2019 and Complete University Guide 2019)
World Top 200 (Times Higher Education World University Rankings 2019)

[TEF Gold logo RGB]  [cid:image002.png@01D2E051.A6A10930]  [facebook] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.facebook.com%2Fueaofficial&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607326917&sdata=pyTQ9kfX%2BGVzLQaVA36zvRz3NUKNzsZGgl1qB8A0ERs%3D&reserved=0>   [twitter-old] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.twitter.com%2Funiofeastanglia&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607336922&sdata=rhW%2FsvtQ8oF6fO2Sx8L5vNM4zZC0nHJ8Xb0xbbcoOfI%3D&reserved=0>  [tumblr] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Funiofeastanglia.tumblr.com%2F&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607346935&sdata=fuOaPhn03UegU%2F1sUCokTaEHgIxIft%2BfcR4rgwbtMzM%3D&reserved=0>  [flickr] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.flickr.com%2Funiofeastanglia&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607346935&sdata=mrnMIt%2F%2FYsYW47VWvIfUPkdtzRWU6aS%2FuOPvpr8N34s%3D&reserved=0>  [linkedin] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fedu%2Fschool%3Fid%3D12699&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607356936&sdata=B1x%2Bm5jSnBykN%2FaeMw%2FOKYc0uQ%2FBOcFjEbfdrDVYruk%3D&reserved=0>  [youtube] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.youtube.com%2Fueaofficial&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607356936&sdata=gJZ6Ghe0W9U9f1WA3lkxzHuf%2BQcCyv70j7pT0BYLmBY%3D&reserved=0>  [cid:image008.png@01CF8BB5.50024060] <https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Finstagram.com%2Funiofeastanglia&data=02%7C01%7CJ.Cassidy%40uea.ac.uk%7C279e7f8be9f146d2518208d65c22b9d5%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C636797701607366940&sdata=t6fhWH3U0kVxtuTFqPD%2B0LtIi1M%2FMHQRPweSGPJoK3E%3D&reserved=0>

Any personal data exchanged as part of this email conversation will be processed by the University in accordance with current UK data protection law and in line with the relevant UEA Privacy Notice.

This email is confidential and may be privileged. If you are not the intended recipient please accept my apologies; please do not disclose, copy or distribute information in this email or take any action in reliance on its contents: to do so is strictly prohibited and may be unlawful. Please inform me that this message has gone astray before deleting it. Thank you for your co-operation.

**Comment by papr** [comment]
I do not know the exact risks of enabling OTG permanently. There must be a reason why OnePlus does not offer this option via the UI. Therefore, I cannot recommend it.

Yes, the home screen shortcut to enable OTG is a good work around which we use as well.

I have not experienced the described camera-shutting-off issue before. I have a few questions in this regard in order to debug the issue:
- Can you consistently reproduce the issue?
- Does the recording continue without the cameras being on?
- Can you check the OTG settings after the cameras were shut off? Is it on or off?
- Which Android/Oxygen version do you use?
- Which Pupil Mobile version do you use?

**Comment by JoeCassidy** [comment]
Hi,

We have been experiencing another issue since resolving the above issue- basically the phones will connect and run mostly fine- but we are experiencing some issues with one of the recordings dropping sporadically.

We are running 2 instances of pupil mobile on 2 OnePlus A5010_NMF26X (5T) phones, which are streaming via a 5G router to a MacBook running pupil capture (again 2 instances, one for each camera/phone). 1 phone is recording both world and eye cam videos, the other is just recording a world view. We have found that after a non-determined amount of time (around 10 mins today when testing), the world view of the eyetracking camera (the one recording both world and eye cams) will stop publishing to the MacBook pupil capture application, and the window which previously showed this world cam for the eyetracker camera will swap and just show a duplicate of the world cam for the other camera/phone.

We then can just see two windows showing the same world cam recording from the world cam only phone. We were able to bring the origional recording back using the pupil caputre software (and it didn't seem to be affected), but we are completely unusure of what is causing this issue. It has happened 3 times recently but has not happened every time that we run a session. When the world cam 'dropped' it was listed as 'idle' on the pupilmobile software before it came back recording, and the OTG settings still appeared to be on on both phones after the 10 min window.

I would be grateful if you could please advise on anything to fix/test the above issue!

Many thanks again,

Kind regards,

Joe
