### ISSUE TITLE
Pupil Mobile App On IOS

### ISSUE THREAD

**Issue by graceshaib** [pupil-labs/pupil-mobile-app#38]
Hello,

I was wondering if anyone managed to download the pupil mobile app on IOS since the application is only available on Android softwares. If you are also familiar with a way to do that please let me know. Any help is appreciated.

Thank you!

**Comment by papr** [comment]
Hi, Pupil Mobile for iOS does not exist and there are currently no plans to develop such an application. We can reopen this issue, if this changes.
