### ISSUE TITLE
[Question] how to read *.time files

### ISSUE THREAD

**Issue by fosterseth** [pupil-labs/pupil-mobile-app#5]
When recording locally to android device, there are two *.time files, which I assume to be the system clock timestamps of each frame. What is the encoding of those files -- numpy could not read them. I tried a base64 decoder but that didn't return anything meaningful.

Thanks

**Comment by fosterseth** [comment]
I may have figured it out. I think it's big-endian 32-bits unsigned int

in python
```
f = open("eye.time", "rb")
struct.unpack('>I', f.read(4))
```
seems to return something reasonable.

**Comment by fosterseth** [comment]
further followup,

You need to pack to long, then unpack to float to get an accurate timestamp, as this is how java's intBitsToFloat works. See this discussion, http://stackoverflow.com/questions/30124608/convert-unsigned-integer-to-float-in-python
```
 x = struct.unpack('>I', f.read(4))
 y = struct.pack('>l', x[0])
 z = struct.unpack('>f', y)
```

**Comment by papr** [comment]
Sorry for the delayed comment. Timestamps are written as big-endian 32-bit floats. The easiest way to read all tiemstamps is to use numpy:

```python
import numpy
# `timestamp_file_location` is the path to the tiemstamp fiel you try to load
timestamps = numpy.fromfile(timestamp_file_location, dtype=numpy.dtype('>f4'))
```

**Comment by fosterseth** [comment]
ah this no longer works for me, as of the latest Pupil Mobile app (0.9.2). I also did an Android system update to 7.1.2 recently, but I can't imagine that would affect the timestamps.

Here is what I get now from the *.time files, using the numpy.fromfile(file, dtype='>f4') command,

```
4.986387
289285898240.000000
4.986396
-243525207490385208314112309412757504.000000
4.986406
-0.000000
4.986416
0.000000
4.986422
237312680132608.000000
4.986426
-0.000000
4.986432
```
etc.

Any suggestions?

**Comment by papr** [comment]
Yes, this is our bad for not communicating this change, well enough. We changed the time stamp precision to 64 bit floats. Change `>f4` to `>f8` and it will work fine.

**Comment by mkassner** [comment]
@papr  actually its 64bit little endian.

```python
import numpy
# `timestamp_file_location` is the path to the tiemstamp fiel you try to load
timestamps = numpy.fromfile(timestamp_file_location, dtype=np.float64)
```
