### ISSUE TITLE
Connecting to Pupil Mobile from Pupil Capture

### ISSUE THREAD

**Issue by alexander-pastukhov** [pupil-labs/pupil-mobile-app#8]
Hi,

I am trying to connect from Pupil Capture (pupil_capture_windows_x64_v0.9.14-7)  to Pupil Mobile (0.17.0) running at Nexus 5X phone (Android 7.1.1, build number NMF26F). The Pupil Mobile shows both the world cam (Pupil Cam1 ID2) and the eye cam (Pupil Cam ID0), and records (or, at least, looks like it is recording). However, I do not understand how to connect to it from Pupil Capture to perform the calibration, recording, etc. I select "Pupil Mobile" in Capture Selection/Manager but "Remote host" always stays as "No hosts found".  Both the phone and the PC are connected to the university WiFi network. Are there are more specific restrictions?

Would be very grateful for any help!
Alexander (Sasha) Pastukhov

**Comment by papr** [comment]
Hey @alexander-pastukhov 
Pupil Capture and Pupil Mobile use the [`ZRE` protocol](https://rfc.zeromq.org/spec:36/ZRE/) to automatically find each other. The protocol uses an UDP beacon to do so. It is very probable that your university wifi is configured to drop UDP traffic. Therefore, auto-detection does not work.

We recommend using a local ad-hoc wifi network (mobile hotspot) in such cases.

**Comment by alexander-pastukhov** [comment]
Hey @papr,

not sure what I am doing wrong but I still cannot make them see each other :( I've tried:
1) local network via a wireless router I found (I don't know admin password, so I do not have any control over it, just connecting both) - nope.
2) hotspot on my phone with cellular traffic off: both computer and the Nexus phone connect, but "No hosts found" remains.
3) hotspot on the Nexus phone itself (don't know if that even makes sense), again, nothing.

Could you be more specific on how should I set the mobile hotstop up and what diagnostics should I be looking at?

**Comment by papr** [comment]
@alexander-pastukhov Which Pupil Mobile and Pupil Capture versions are you using? From your description, it looks like you have the network setup correctly.

**Comment by alexander-pastukhov** [comment]
@papr Turns out the problem was with the Uni-issued version of Win10. Used my private laptop using my phone as a hotspot as a link between the laptop and Nexus and everything worked like a charm. Thank you for your help!
